apiVersion: v1
kind: ServiceAccount
metadata:
  name: dockerhub-builder
secrets:
  - name: dockerhub-docker-config
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline
spec:
  description: |
    Builds and publishes a docker image based on a git repo
  params:
  - name: repo-url
    type: string
    description: The git repository URL to clone from.
  - name: branch-name
    type: string
    description: The git branch to clone.
  - name: image
    type: string
    description: "The image uri (ex: CONTAINER_URL/IMAGE_NAME:TAG)."
  workspaces:
  - name: shared-data
    description: |
      This workspace will receive the cloned git repo and be passed
      to the next Task for the repo's README.md file to be read.
  - name: dockerconfig
    description: |
      This workspace will receive the docker config secret.
  tasks:
  - name: git-clone-task
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-data
    params:
    - name: url
      value: $(params.repo-url)
    - name: revision
      value: $(params.branch-name)
  - name: source-to-image
    taskRef:
      name: kaniko
    runAfter:
      - git-clone-task
    workspaces:
      - name: source
        workspace: shared-data
      - name: dockerconfig
        workspace: dockerconfig
    params:
      - name: IMAGE
        value: $(params.image)

---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pipeline-main
spec:
  serviceAccountName: dockerhub-builder
  pipelineRef:
    name: pipeline
  workspaces:
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  - name: dockerconfig
    secret:
      secretName: dockerhub-docker-config
      items:
          - key: .dockerconfigjson
            path: config.json
  params:
  - name: repo-url 
    value: "{{REPO_URL}}"
  - name: branch-name
    value: "{{BRANCH_NAME}}"
  - name: image
    value: "{{IMAGE}}:{{IMAGE_TAG}}"
